version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: ../build/Dockerfile.server
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_URL=${GEMINI_URL}

  client:
    build:
      context: ./client
      dockerfile: ../build/Dockerfile.client
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - PORT=${CLIENT_PORT}